### ISSUE TITLE
error when trying to use markAsType(Child.class) or (Adult.class).

### ISSUE THREAD

**Issue by jmbjr** [jmbjr/JALSE-SimFarm#2]
checkout and run commit: c6ef5f1405007a07f8ec5dacd344b2c3529d7833

in jmbjr.simland.actions.GrowAnimals.java, line 33, get the following exceptions:

`Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy10.markAsType(Unknown Source)
	at jmbjr.simland.actions.GrowAnimals.checkIfAdult(GrowAnimals.java:37)
	at jmbjr.simland.FarmPanel.addAnimalAtRandomPosition(FarmPanel.java:95)
	at jmbjr.simland.FarmPanel.reset(FarmPanel.java:201)
	at jmbjr.simland.FarmPanel.createEntities(FarmPanel.java:124)
	at jmbjr.simland.FarmPanel.<init>(FarmPanel.java:58)
	at jmbjr.simland.SimFarm.main(SimFarm.java:13)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jalse.entities.DefaultEntityProxyFactory$EntityProxyHandler.invoke(DefaultEntityProxyFactory.java:173)
	... 7 more
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy3.entityMarkedAsType(Unknown Source)
	at jalse.entities.DefaultEntity.markAsType(DefaultEntity.java:342)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at jalse.misc.ListenerSet.invoke(ListenerSet.java:71)
	... 14 more
Caused by: java.lang.NullPointerException
	at jmbjr.simland.AnimalProperties$PersonProperties.access$0(AnimalProperties.java:19)
	at jmbjr.simland.AnimalProperties.getColour(AnimalProperties.java:49)
	at jmbjr.simland.entities.TransformationListener.entityMarkedAsType(TransformationListener.java:15)
	... 19 more
`

here's the function:

`	public static void checkIfAdult(Animal animal) {

		if (animal.getSize() >= AnimalProperties.getSize()) {
			//adult
			animal.markAsType(Adult.class);
			animal.unmarkAsType(Child.class);
		} else {
			//child
			animal.markAsType(Child.class);
			animal.unmarkAsType(Adult.class);
		}
	}`

as we create each animal, we send it off to this function to see if should be flagged as an adult.

Child.class and Adult.class are interfaces that extend Animal (which is itself an entity that extends Entity).

I have two other entities, Grazer and Rester, and these work just fine elsewhere in the code and in the location above if I swap out Child and Adult.

**Comment by jmbjr** [comment]
issue was forgetting to set up the data in AnimalProperties.java

doh
